In [4]:

import cv2
import mediapipe as mp
import numpy as np
from tensorflow.keras.models import load_model

happy = ""
top = -1
    
# Define actions and corresponding labels
actions = ['j','u','p','pp']
seq_length = 30

model = load_model('models/model.h5')

mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
hands = mp_hands.Hands(
    max_num_hands=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

cap = cv2.VideoCapture(0)

seq = []
action_seq = []

while cap.isOpened():
    ret, img = cap.read()
    img0 = img.copy()
    
    
    img = cv2.flip(img, 1)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    result = hands.process(img)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    
    # cv2.putText(img,f'hi', org=[50,50], fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1, color=(255, 255, 255), thickness=2)
    

    if result.multi_hand_landmarks is not None:
        
    
        for res in result.multi_hand_landmarks:
            joint = np.zeros((21, 4))
            for j, lm in enumerate(res.landmark):
                joint[j] = [lm.x, lm.y, lm.z, lm.visibility]
                
            check = joint[5][0] - joint[17][0]
            point = joint[5][0] - joint[0][0]
                    
                    
            comp_tip_1 = joint[[4,8,12,16], 0:1]    
            comp_tip_2 = joint[[8,12,16,20], 0:1]
                                       
            tip_to_tip = comp_tip_1 - comp_tip_2
                               
            tip_to_tip = tip_to_tip / np.linalg.norm(tip_to_tip)                              
                                       
            zero = joint[[0,0,0,0,0], 1:2 ]
            tip = joint[[4,8,12,16,20], 1:2]
                    
            zero_to_tip = zero - tip
            zero_to_tip = zero_to_tip / np.linalg.norm(zero_to_tip)
                    

                    # Compute angles between joints
            v1 = joint[[0,1,2,3,0,5,6,7,0,9,10,11,0,13,14,15,0,17,18,19], :3] # Parent joint
            v2 = joint[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], :3] # Child joint
                    
            v = v2 - v1 # [20, 3]
                    # Normalize v
            v = v / np.linalg.norm(v, axis=1)[:, np.newaxis]

                    # Get angle using arcos of dot product
            angle = np.arccos(np.einsum('nt,nt->n',
                v[[0,1,2,4,5,6,8,9,10,12,13,14,16,17,18],:], 
                v[[1,2,3,5,6,7,9,10,11,13,14,15,17,18,19],:])) # [15,]

            angle = np.degrees(angle) # Convert radian to degree
      
            d = np.append(v.flatten(), check)
            d = np.append(d, point)
            d = np.append(d,zero_to_tip)
            d = np.append(d,tip_to_tip)
            
            
            #d = np.concatenate([joint.flatten(), d])
            
            
            d = np.concatenate([d, angle])

                    #d = np.concatenate([joint.flatten(), angle_label])
                    #d = np.concatenate([d, check])
                    
                    
            print(d.shape)
            
            seq.append(d)

            mp_drawing.draw_landmarks(img, res, mp_hands.HAND_CONNECTIONS)

            if len(seq) < seq_length:
                continue
                
         

            input_data = np.expand_dims(np.array(seq[-seq_length:], dtype=np.float32), axis=0)
            print(input_data.shape)
            y_pred = model.predict(input_data).squeeze()
            print(y_pred)

            i_pred = int(np.argmax(y_pred))
            conf = y_pred[i_pred]
            
#             cv2.putText(img, 'yes!!', org=[25,50],
#                     fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1, color=(255, 255, 255), thickness=2)

            if conf < 0.95:
                continue

            action = actions[i_pred]
            action_seq.append(action)

            if len(action_seq) < 3:
                continue

            this_action = '?'
            if action_seq[-1] == action_seq[-2] == action_seq[-3]: # 정확한 액션이라면
                this_action = action
                
                #org=(int(res.landmark[0].x * img.shape[1])
                
            
            print(this_action)
            
            if cv2.waitKey(1) == ord('a'):
                if this_action == 'space':
                    this_action = " "
                    happy = happy + this_action
                    top +=1
                    
                if this_action =='backspace':
                    happy = happy[:-1]
                    print(happy)
                    
                else:
                    happy = happy + this_action.upper() # upper() 대문자 변환 함수
                    top += 1
                
            cv2.putText(img, f'{this_action.upper()}', org=[25,50],
                        fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1, color=(255, 255, 255), thickness=2)
          
            # happy = ''.join(str(_) for _ in happy)
            print(type(happy))
             
            cv2.putText(img , happy , org=[25,450], fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1, color=(255, 255, 255), thickness=2)        
            cv2.imshow('img', img)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 393ms/step
[2.9806858e-01 8.4256007e-09 9.1303356e-21 7.0193142e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 34ms/step
[4.7681424e-01 1.0036442e-09 1.8002377e-14 5.2318579e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 40ms/step
[9.9999619e-01 4.2928916e-19 8.2255808e-25 3.8557901e-06]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 43ms/step
[9.99897122e-01 1.27216895e-14 1.77622516e-21 1.02911770e-04]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 33ms/step
[9.99995708e-01 3.82596444e-17 1.28185156e-23 4.31268018e-06]
j
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[9.5982397e-01 1.3740871e-08 2.8050189e-20 4.0176041e-02]
j
<class 'str'>
(86,)
(1, 30, 86)

1/1 [==============================] - 0s 25ms/step
[7.9984850e-01 8.8873952e-05 2.7203206e-02 1.7285949e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[6.8208563e-01 1.9413768e-04 6.6637315e-02 2.5108290e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[0.80494106 0.0023242  0.04326648 0.14946821]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[0.69084406 0.00248229 0.1323301  0.17434354]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.6824596  0.00211234 0.2037068  0.11172122]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.55916053 0.00170837 0.3706844  0.06844666]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.66784066 0.00173007 0.3192259  0.01120346]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[0.52999544 0.0009897  0.43160623 0.03740859]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/s

(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[0.18124793 0.01520621 0.42145288 0.38209298]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 18ms/step
[0.16329178 0.01287153 0.49701887 0.32681775]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[0.08113533 0.11372736 0.28317496 0.5219624 ]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 27ms/step
[0.07814512 0.056343   0.38388997 0.4816219 ]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[0.01017142 0.5513586  0.03493712 0.40353286]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[0.05188902 0.7643922  0.16270651 0.02101237]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[3.7380990e-03 3.6431840e-01 4.1696612e-07 6.3194317e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.09516346 0.8368591  0.00111303 0.06686432]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 16ms/step
[1.8467952e-02 3.7569428e-04 1.3127815e-04 9.8102504e-01]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[2.0612022e-02 1.1332284e-04 9.0034300e-05 9.7918463e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[2.0587914e-02 4.1219235e-05 9.2246308e-05 9.7927856e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[4.5697555e-02 6.1856597e-05 1.5481406e-04 9.5408571e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 26ms/step
[3.5932560e-02 2.2108461e-05 1.4291955e-04 9.6390247e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[3.0194465e-02 4.8286223e-05 2.1091380e-04 9.6954632e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[4.9547452e-02 9.2796850e-05 2.1833493e-04 9.5014149e-01]
pp
<class 'str'>
(86,

1/1 [==============================] - 0s 24ms/step
[2.2327627e-05 1.2283014e-29 1.0446549e-07 9.9997759e-01]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 19ms/step
[9.9711454e-01 8.3689463e-13 2.8854983e-03 1.8944512e-08]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[9.9982291e-01 1.5199562e-13 1.7707441e-04 9.2185672e-09]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[9.999206e-01 7.365141e-15 7.942200e-05 1.077943e-08]
j
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 27ms/step
[4.2893626e-05 5.3353784e-31 6.6757971e-01 3.3237743e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[9.5127875e-01 1.2781266e-11 4.8721146e-02 8.2839520e-08]
j
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[9.9973613e-01 1.8428920e-13 2.6389572e-04 2.2298433e-10]
j
<class 'str'>
(86,)
(1, 30, 86)
1/1 [=======

1/1 [==============================] - 0s 24ms/step
[4.3412463e-05 5.2639111e-18 1.6893442e-22 9.9995661e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[5.7068573e-06 1.7785576e-17 3.3364543e-22 9.9999428e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[7.3822775e-08 1.2545441e-15 9.3113738e-20 9.9999988e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[1.4160901e-09 2.1303453e-20 5.7967714e-23 1.0000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[8.0070539e-10 1.2001241e-18 2.1302945e-22 1.0000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[4.1948533e-06 2.0721686e-22 7.0363538e-25 9.9999583e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 20ms/step
[4.0567451e-07 1.5449144e-19 5.1924110e-21 9.9999964e-01]
pp
<class 'str'>
(86

1/1 [==============================] - 0s 25ms/step
[2.7721584e-12 3.0913556e-13 1.1611862e-20 1.0000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[1.46283799e-12 1.54684791e-13 1.25697445e-20 1.00000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.9125813e-13 2.6538837e-16 2.6984035e-23 1.0000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[2.4720073e-06 1.0705669e-09 3.2642588e-18 9.9999750e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 19ms/step
[1.8649421e-15 5.5366630e-14 2.8791866e-20 1.0000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.09691295e-13 8.47430199e-13 1.80956784e-19 1.00000000e+00]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 20ms/step
[1.0940729e-10 8.3892997e-11 4.3966105e-17 1.0000000e+00]
pp
<class 's

1/1 [==============================] - 0s 17ms/step
[0.05275385 0.7466406  0.01687458 0.18373097]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[0.02382027 0.74004215 0.01732684 0.21881074]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.02579618 0.7799396  0.01281033 0.18145391]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.01524714 0.79364336 0.01154095 0.1795686 ]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.02494407 0.704807   0.02745106 0.24279788]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[0.03713019 0.5792243  0.06567126 0.31797427]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.17002445 0.26018256 0.17080304 0.39898995]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.02941336 0.05175238 0.41889226 0.49994195]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[0.0567526  0.084949

[0.00345943 0.02209057 0.2683248  0.7061252 ]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[7.227026e-04 4.702146e-03 7.220965e-02 9.223655e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[0.02782258 0.06464118 0.1810824  0.7264539 ]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[0.02886728 0.05871869 0.07560159 0.83681244]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 28ms/step
[0.00155337 0.00746087 0.02617274 0.964813  ]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[1.1838600e-06 1.7339794e-04 1.1331417e-02 9.8849410e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[1.4985167e-05 1.1230246e-03 6.9598039e-04 9.9816602e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 33ms/step
[3.45848491e-07 1.11193396e-04 8.21454078e-03 9.91673887e-01]
pp
<class 'str'>
(86,)
(1, 30, 86)
1/1 [===

[1.7541523e-01 1.6532742e-05 9.4085129e-07 8.2456726e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 19ms/step
[5.7450008e-02 1.1076047e-09 2.2966713e-06 9.4254762e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[3.3422079e-02 5.0198701e-10 1.2480596e-06 9.6657670e-01]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[1.7158541e-01 1.1263612e-09 8.8755814e-06 8.2840574e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 33ms/step
[3.1527472e-01 2.1045206e-09 2.2919785e-06 6.8472296e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 23ms/step
[3.6692092e-01 2.5132891e-09 2.9050434e-06 6.3307619e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.3380498e-01 1.0680723e-08 1.3549910e-05 8.6618143e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 26ms/step
[1.9697957e-01 2.3781178e-08 1.6070609e-05 8.0300432e-01]
(86,)
(1, 30, 86)
1/1 [=======

1/1 [==============================] - 0s 24ms/step
[6.6628277e-02 2.5918887e-11 9.3334943e-01 2.2204600e-05]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[8.7242562e-01 8.2009931e-13 1.2743333e-01 1.4105400e-04]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[4.1215736e-01 6.1969955e-13 5.8778858e-01 5.4099808e-05]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[9.7939931e-02 2.7910221e-10 9.0205413e-01 5.8917199e-06]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[7.1182116e-03 7.7425653e-13 9.9288058e-01 1.1884731e-06]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[3.2710388e-02 2.4935118e-11 9.6728802e-01 1.6079692e-06]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[3.1437378e-02 1.5417789e-11 9.6855420e-01 8.4360636e-06]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[5.1

1/1 [==============================] - 0s 24ms/step
[4.7949576e-17 2.7045582e-36 1.5933319e-03 9.9840671e-01]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[2.7090360e-17 1.6671551e-33 9.6811032e-01 3.1889699e-02]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 18ms/step
[2.4448274e-19 8.1907562e-31 9.9926633e-01 7.3368230e-04]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[3.05069814e-18 1.10500315e-26 9.90206659e-01 9.79337003e-03]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[3.939327e-17 8.982737e-25 9.990250e-01 9.749742e-04]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[2.4038333e-15 6.0040832e-22 9.9055487e-01 9.4450824e-03]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.0720289e-08 1.9376660e-14 6.1324020e-03 9.9386758e-01]
?
<class 'str'>
(86,)
(1, 

[9.3670166e-01 6.2032886e-02 7.2139641e-14 1.2655027e-03]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[5.5714083e-22 1.0000000e+00 1.2434926e-34 4.3506151e-31]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[4.2470437e-17 1.0000000e+00 5.5186145e-36 1.6828636e-29]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[1.1501552e-14 1.0000000e+00 2.8973166e-31 2.8130174e-19]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[2.1799517e-11 1.0000000e+00 1.4373712e-30 3.1672141e-20]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.1747908e-09 1.0000000e+00 2.2306037e-31 6.0358366e-22]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 28ms/step
[2.3349676e-06 9.9999762e-01 0.0000000e+00 2.4006498e-19]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[7.23942

1/1 [==============================] - 0s 17ms/step
[8.7915152e-01 1.0136038e-17 1.2084846e-01 4.9718778e-11]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[7.8620648e-01 2.7864135e-19 2.1379349e-01 1.1034054e-09]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 27ms/step
[7.4363303e-01 7.0995250e-04 2.5490117e-01 7.5579819e-04]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 18ms/step
[0.2741669  0.6429571  0.0760983  0.00677773]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 18ms/step
[6.2236068e-04 9.7337900e-18 9.9937516e-01 2.5607749e-06]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[1.0421711e-01 3.3235585e-04 8.9519280e-01 2.5780802e-04]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[9.9999249e-01 7.6788285e-16 7.4560407e-06 1.0764839e-15]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 21ms/step
[1.2189302e-03 6.3454259e-10 9.9

1/1 [==============================] - 0s 16ms/step
[6.0706767e-03 8.8547735e-04 9.6378851e-01 2.9255275e-02]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[9.2175525e-01 9.9449851e-11 7.8244731e-02 3.9026078e-12]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 32ms/step
[3.0526176e-02 7.0522576e-20 9.6947384e-01 2.9929101e-09]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[4.9452248e-01 7.0186368e-23 5.0546193e-01 1.5525929e-05]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[8.8444978e-02 1.8199695e-12 9.1155505e-01 4.7124895e-09]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[8.5254377e-01 8.3176025e-22 1.4741954e-01 3.6638958e-05]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[1.4068690e-03 1.8300311e-10 9.9858046e-01 1.2720308e-05]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.9

<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[2.8981499e-03 9.1493440e-01 2.4103521e-11 8.2167394e-02]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[1.0646491e-03 9.9663711e-01 7.2644421e-12 2.2982352e-03]
?
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[5.749135e-04 9.993893e-01 5.159559e-12 3.577495e-05]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[1.4930742e-04 9.9984312e-01 1.4769280e-12 7.4632781e-06]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 16ms/step
[7.5274518e-05 9.9992335e-01 2.2872446e-12 1.4513265e-06]
u
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[9.8816961e-02 9.0105098e-01 1.8968045e-07 1.3186577e-04]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[0.8463686  0.01737535 0.10703453 0.02922149]
(86,)
(1, 30, 86)
1/1 [===================

1/1 [==============================] - 0s 32ms/step
[2.5423772e-15 0.0000000e+00 9.9880087e-01 1.1990645e-03]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[9.0814002e-16 0.0000000e+00 9.9980432e-01 1.9565884e-04]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.4138302e-15 0.0000000e+00 9.9955434e-01 4.4558989e-04]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 33ms/step
[1.2376836e-14 0.0000000e+00 9.9852437e-01 1.4757128e-03]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 24ms/step
[1.07713304e-13 0.00000000e+00 9.98409748e-01 1.59025355e-03]
p
<class 'str'>
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 17ms/step
[5.54604323e-13 6.11448076e-30 1.17888026e-01 8.82111967e-01]
(86,)
(1, 30, 86)
1/1 [==============================] - 0s 25ms/step
[3.3282319e-03 9.2371032e-08 4.5112504e-08 9.9667156e-01]
?
<class 'str'>
(86,)
(1, 30, 86)
